### ISSUE TITLE
Update/delete post

### ISSUE THREAD

**Issue by arbianchi** [rubyforgood/doublehranch#123]

**Comment by maebeale** [comment]
No existing views or controller actions for edit or delete.

**Comment by jk1dd** [comment]
I'd be interested in taking this on - is anyone else working on it currently??

**Comment by kalimar** [comment]
I don't think so - have at it!

**Comment by maebeale** [comment]
Thanks, Adina!!! FYI few of us have checked out stuff (to no avail) related
to ImageMagick for the create action. I don't think it should affect
update/delete, but may if the user is trying to change the photo.

On Jul 5, 2017 2:56 PM, "Kalimar Maia" <notifications@github.com> wrote:

I don't think so - have at it!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/rubyforgood/doublehranch/issues/123#issuecomment-313194500>,
or mute the thread

**Comment by jk1dd** [comment]
Hi! Quick question - what should I be using for AWS credentials when developing here? I've used AWS with paperclip before, but had my own bucket and creds that I set up. How does that work with an opensource project?

Basically, the problem is I can't create a post (and therefore am not able to confirm my ability to update or delete it!)

**Comment by kalimar** [comment]
Hi Jonathan,
I'm not at my computer yet but you should be able to create a local . Env
file with your credentials and test locally. Let me know if you have
questions.
Kalimar

**Comment by jk1dd** [comment]
Hi! I just opened a pull request for this - let me know of any questions or comments.

**Comment by kalimar** [comment]
Thanks Jonathan! I'll take a look tomorrow morning.
Regards,
Kalimar
